# Generated by Django 4.2.1 on 2023-05-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_product_description_alter_product_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("tel", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
            ],
        ),
    ]
