# Generated by Django 4.2.1 on 2023-05-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_rename_categories_categorie"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("detail", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("done", models.CharField(max_length=200)),
                ("summary", models.CharField(max_length=200)),
            ],
        ),
    ]
