# Generated by Django 4.2.1 on 2023-05-16 05:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_customerform"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerform",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customerform",
            name="detail",
            field=models.TextField(blank=True, null=True, verbose_name="รายละเอียด"),
        ),
        migrations.AlterField(
            model_name="customerform",
            name="done",
            field=models.BooleanField(
                default=False, verbose_name="ปัญหาแก้ปัญหาจบแล้วหรือไม่"
            ),
        ),
        migrations.AlterField(
            model_name="customerform",
            name="email",
            field=models.CharField(
                max_length=200, verbose_name="อีเมลสำหรับติดต่อกลับ"
            ),
        ),
        migrations.AlterField(
            model_name="customerform",
            name="name",
            field=models.CharField(max_length=200, verbose_name="ชื่อผู้ถาม (name)"),
        ),
        migrations.AlterField(
            model_name="customerform",
            name="summary",
            field=models.TextField(
                blank=True, default="", null=True, verbose_name="สรุปปัญหา วิธีแก้ไข"
            ),
        ),
        migrations.AlterField(
            model_name="customerform",
            name="title",
            field=models.CharField(max_length=200, verbose_name="ประเภทปัญหา"),
        ),
    ]
