# Generated by Django 4.2.1 on 2023-05-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_customerform_created_at_alter_customerform_detail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerform",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
