# Generated by Django 4.2.1 on 2023-05-16 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_alter_customerform_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instock",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "sold",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.product",
                    ),
                ),
            ],
        ),
    ]
