# Generated by Django 4.2.1 on 2023-05-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_country_director_genre_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="ชื่อสินค้า"),
        ),
    ]
