# Generated by Django 4.2.1 on 2023-05-27 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_alter_product_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="country",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="director",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="genre",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="Director",
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
        migrations.DeleteModel(
            name="Movie",
        ),
    ]
